version: '2'
services:
    hipsterviti-app:
        image: hipsterviti
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hipsterviti-mysql:3306/hipsterviti?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hipsterviti-mysql:
        extends:
            file: mysql.yml
            service: hipsterviti-mysql
